"""Permission should be duplicated in permissions.py and permissions.zcml
"""

AddClinicalAliquot = "LIMS: Add Clinical Aliquot"
AddClinicalSample = "LIMS: Add Clinical Sample"
AddCommercialBox = "LIMS: Add Commercial Box"
AddCustomerServiceCall = "LIMS: Add Customer Service Call"
AddEightFrameRun = "LIMS: Add Eight Frame Run"
AddFreezer = "LIMS: Add Freezer"
AddiChip = "LIMS: Add iChip"
AddiChipAssay = "LIMS: Add iChip Assay"
AddiChipLot = "LIMS: Add iChip Lot"
AddMaterial = "LIMS: Add Material"
AddNCE = "LIMS: Add NCE"
AddNoFrameRun = "LIMS: Add No Frame Run"
AddPatient = "LIMS: Add Patient"
AddPlate = "LIMS: Add Plate"
AddProvider = "LIMS: Add Provider"
AddQCAliquot = "LIMS: Add Quality Control Aliquot"
AddQCSample = "LIMS: Add Quality Control Sample"
AddRack = "LIMS: Add Rack"
AddRandDAliquot = "LIMS: Add Research and Development Aliquot"
AddRandDBox = "LIMS: Add RandD Box"
AddRandDSample = "LIMS: Add Research and Development Sample"
AddShelf = "LIMS: Add Shelf"
AddSite = "LIMS: Add Site"
AddSolution = "LIMS: Add Solution"
AddTestRun = "LIMS: Add Test Run"
AddThreeFrameRun = "LIMS: Add Three Frame Run"
AddVeracisRunBase = "LIMS: Add Veracis Run Base"
