"""Permission should be duplicated in permissions.py and permissions.zcml
"""

AddMaterial = "LIMS: Add Material"
AddSolution = "LIMS: Add Solution"
AddiChipLot = "LIMS: Add iChip Lot"
AddiChip = "LIMS: Add iChip"
AddWorklist = "LIMS: Add Worklist"
AddPlate = "LIMS: Add Plate"
AddNCE = "LIMS: Add NCE"
AddPatient = "LIMS: Add Patient"
AddProvider = "LIMS: Add Provider"
AddClinicalSample = "LIMS: Add Clinical Sample"
AddRandDSample ="LIMS: Add Research and Development Samples"
AddiChipAssay = "LIMS: Add iChip Assay"
AddCustomerServiceCall = "LIMS: Add Customer Service Call"
