"""Permission should be duplicated in permissions.py and permissions.zcml
"""

AddMaterial = "LIMS: Add Material"
AddSolution = "LIMS: Add Solution"
AddiChipLot = "LIMS: Add iChip Lot"
AddiChip = "LIMS: Add iChip"
AddTestRun = "LIMS: Add Test Run"
AddPlate = "LIMS: Add Plate"
AddNCE = "LIMS: Add NCE"
AddPatient = "LIMS: Add Patient"
AddProvider = "LIMS: Add Provider"
AddClinicalSample = "LIMS: Add Clinical Sample"
AddClinicalAliquot = "LIMS: Add Clinical Aliquot"
AddRandDSample = "LIMS: Add Research and Development Sample"
AddRandDAliquot = "LIMS: Add Research and Development Aliquot"
AddiChipAssay = "LIMS: Add iChip Assay"
AddCustomerServiceCall = "LIMS: Add Customer Service Call"
AddFreezer = "LIMS: Add Freezer"
AddShelf = "LIMS: Add Shelf"
AddRack = "LIMS: Add Rack"
AddCommercialBox = "LIMS: Add Commercial Box"
AddRandDBox = "LIMS: Add RandD Box"
AddSite = "LIMS: Add Site"
AddNoFrameRun = "LIMS: Add No Frame Run"
AddEightFrameRun = "LIMS: Add Eight Frame Run"
AddThreeFrameRun = "LIMS: Add Three Frame Run"
AddQCSample = "LIMS: Add Research and Development Sample"
AddQCAliquot = "LIMS: Add Quality Control Aliquot"
